version: "3.4"
services:
  jenkins:
    build: .
    network_mode: host
    image: be.doji.productivity/jenkins:lts-alpine
    ports:
      - 8080:8080
    volumes:
      - jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "trambu:192.168.0.1"

volumes:
  jenkins-volume:

